services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DEV_DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hotel-network
    command:
      - --default-authentication-plugin=mysql_native_password
      - --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    #giói hạn logging (json)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis_hotel:
    image: redis:alpine
    container_name: redis_hotel
    ports:
      - "6379:6379"
    networks:
      - hotel-network
    volumes:
      - redis_data_file_dev:/var/lib/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kafka_hotel:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka_hotel
    depends_on:
      - redis_hotel
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka_hotel:9092,EXTERNAL://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka_hotel:9093'
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  # run_consumer:
  #   build: .
  #   container_name: kafka_consumer_hotel
  #   entrypoint: ["/bin/bash", "-c"]
  #   command: >
  #     python manage.py migrate --noinput &&
  #     python manage.py create_kafka_topic &&
  #     python manage.py kafka_consumer
  #   volumes:
  #     - .:/app
  #     - ./.env:/app/.env
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka_hotel:9092
  #     PYTHONUNBUFFERED: 1
  #     DJANGO_SETTINGS_MODULE: hotel_management.settings
  #   depends_on:
  #     kafka_hotel:
  #       condition: service_healthy
  #     redis_hotel:
  #       condition: service_healthy
  #     mysql-db:
  #       condition: service_healthy
  #     be:
  #       condition: service_started
  #   networks:
  #     - hotel-network
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

  be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel_management_be
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      mysql-db:
        condition: service_healthy
      redis_hotel:
        condition: service_healthy
      kafka_hotel:
        condition: service_healthy
    networks:
      - hotel-network
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    env_file:
    - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery_hotel:
    build:
      context: .
      dockerfile: dockerfile.celery
    container_name: celery_hotel
    volumes:
      - .:/app
      - ./.env:/app/.env
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL_DEV}
      KAFKA_BROKER: kafka_hotel:9092
      PYTHONUNBUFFERED: 1
    depends_on:
      - redis_hotel
      - be
    restart: always
    networks:
      - hotel-network
    command: ["celery", "-A", "hotel_management", "worker", "--loglevel=INFO"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery_beat:
    build:
      context: .
      dockerfile: dockerfile.celery
    container_name: celery_beat
    volumes:
      - .:/app
      - ./.env:/app/.env
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL_DEV}
      KAFKA_BROKER: kafka_hotel:9092
      PYTHONUNBUFFERED: 1
    depends_on:
      - redis_hotel
      - be
    restart: always
    networks:
      - hotel-network
    command: ["celery", "-A", "hotel_management", "beat", "--loglevel=INFO"]

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql-data:
  redis_data_file_dev:
  kafka-data:

networks:
  hotel-network:
    driver: bridge